(function () {
  var WORDS_BY_DIFFICULTY = {
    easy: {
      general: [
        "hund", "katt", "hest", "fugl", "fisk", "bil", "tog", "buss",
        "sykkel", "skole", "jobb", "hus", "hage", "dør", "vindu", "stol",
        "bord", "seng", "lampe", "telefon", "nøkkel", "veske", "sko", "jakke",
        "regn", "snø", "sol", "vind", "ball", "gave", "jeg", "ikke",
        "har", "til", "med", "han", "deg", "for", "meg", "hva",
        "den", "som", "kan", "var", "vil", "skal", "men", "her",
        "bare", "hun", "dere", "ham", "dette", "min", "nei", "vet",
        "kom", "der", "din", "hvor", "fra", "oss", "være", "dem",
        "gjør", "ville", "kommer", "igjen", "alle", "hvorfor", "tror", "hvordan",
        "går", "alt", "opp", "ingen", "får", "hvem", "seg", "gjøre",
        "blir", "takk", "bli", "hadde", "bra", "denne", "henne", "inn",
        "litt", "etter", "kunne", "vel", "skulle", "ved", "aldri", "hei",
        "tilbake", "over", "kanskje", "ble", "god", "man", "også", "selv",
        "nok", "sier", "før", "hans", "sammen", "godt", "gang", "ned",
        "tar", "mer", "dag", "vært", "mitt", "mine", "gjorde", "mye",
        "andre", "sett", "vær", "hele", "enn", "ditt", "komme", "deres",
        "hold", "mann", "fordi", "fikk", "mot", "vent", "ting", "tre",
        "gjort", "snakke", "mange", "folk", "hjem", "sant", "tid", "rett",
        "dra", "alltid", "sånn", "unnskyld", "morgen", "bedre", "virkelig", "elsker",
        "tok", "burde", "vår", "hit", "uten", "veldig", "død", "finne",
        "står", "ingenting", "snakker", "sin", "akkurat", "gikk", "kveld", "samme",
        "første", "hør", "kjenner", "hjelpe", "disse", "sted", "vite", "gud",
        "klar", "slik", "lenge", "forstår", "skjer", "hjelp", "under", "fint",
        "eneste", "gir", "holder", "liv", "hallo", "tro", "feil", "snill",
        "hver", "høre", "verden", "døde", "tak", "herregud", "pappa", "holde",
        "rundt", "hører", "redd", "blitt", "stor", "hos", "drepe", "dit",
        "mamma", "borte", "først", "lille", "fant", "heller", "beste", "sikker",
        "drar", "slutt", "bort", "fem", "like", "annet", "tatt", "bør",
        "fått", "vekk", "store", "gjerne", "finner", "fortelle", "våre", "nye",
        "glad", "måtte", "neste", "orden", "navn", "faren", "mannen", "annen",
        "sagt", "gamle", "gjennom", "derfor", "lei", "lenger", "unna", "hatt",
        "stille", "fire", "klarer", "langt", "ennå", "skjønner", "gutt", "par",
        "slå", "klart", "føler", "ett", "herfra", "engang", "meget", "sitt",
        "flott", "hørt", "natt", "gode", "dagen", "hjemme", "faktisk", "kjære",
        "fort", "dollar", "ganger", "galt", "begge", "klare", "mens", "hvilken",
        "bak", "ferdig", "pokker", "vise", "fyr", "tenk", "prøve", "skyld",
        "gammel", "grunn", "drept", "allerede", "rolig", "dårlig", "kommet", "kun",
        "kaptein", "vårt", "hende", "hverandre", "begynner", "jobber", "sine", "mennesker",
        "hyggelig", "del", "bor", "fortell", "ord", "tenker", "fortsatt", "slipp",
        "egen", "stå", "vente", "kvinne", "spiller", "øyeblikk", "ganske", "slapp",
        "måte", "seks", "tenkt", "stopp", "nettopp", "møte", "velkommen", "riktig",
        "kone", "stemmer", "glem", "sønn", "spise", "jente", "redde", "problem",
        "spør", "fin", "vanskelig", "selvfølgelig", "ring", "bruke", "legg", "leve",
        "gått", "kjeft", "tenke", "spille", "lang", "jenta", "lett", "oppe",
        "sent", "moren", "all", "ringe", "ber", "lever", "saken", "full",
        "nytt", "viktig", "pass", "hente", "fast", "mat", "setter", "prøv",
        "uansett", "mellom", "dreper", "åpne", "treffe", "herr", "fly", "fred",
        "dro", "best", "tur", "spørsmål", "fantastisk", "fremdeles", "holdt", "fri",
        "fram", "syns", "skje", "egentlig", "familie", "finnes", "hater", "sette",
        "kjører", "utenfor", "forsiktig", "hvert", "imot", "mest", "gal", "mulig",
        "lar", "kaller", "mit", "satt", "tusen", "bruker", "kjøre", "time",
        "straks", "mindre", "unge", "selvsagt", "spørre", "uke", "løp", "vann",
        "foran", "nogen", "ønske", "driver", "sjanse", "snakk", "vis", "lite",
        "altså", "lære", "gift", "passer", "høres", "nummer", "lyst", "lover",
        "rom", "harry", "dum", "ekte", "huske", "idiot", "fins", "lykke",
        "perfekt", "lov", "våpen", "kjent", "betale", "svar", "lage", "stoppe",
        "sove", "sådan", "gitt", "små", "venstre", "slår", "farvel", "charlie",
        "tale", "blod", "fortsett", "hjelper", "sender", "land", "herre", "hent",
        "hånd", "viser", "finn", "kjør", "ben", "handler", "fortalt", "reise",
        "york", "valg", "tidlig", "bruk", "stund", "blev", "skai", "skrive",
        "tide", "morsomt", "datter", "skyte", "kort", "husk", "jobbe", "skyt",
        "frank", "stadig", "doktor", "kjøpe", "live", "middag", "lager", "henter",
        "legge", "synd", "sitte", "forstå", "masse", "kjærlighet", "peter", "følge",
        "rør", "begynne", "slo", "skynd", "tjeneste", "jøss", "vakker", "sige",
        "ung", "likte", "døren", "gifte", "sende", "hardt", "skikkelig", "frem",
        "skyter", "skutt", "laver", "nær", "syk", "stikker", "betaler", "sekunder",
        "farlig", "høyre", "drikke", "eget", "sist", "general", "intet", "krig",
        "fall", "stikke", "hen", "pris", "blive", "døra", "leter", "større",
        "forklare", "avtale", "sint", "likevel", "svarte", "onkel", "fare", "sak",
        "david", "baby", "forbi", "bekymret", "rette", "dame", "drittsekk", "følg",
        "fengsel", "skade", "enkelt", "slippe", "åtte", "egne", "hjerte", "særlig",
        "drink", "menneske", "endelig", "skjøt", "slåss", "spurte", "stole", "ofte",
        "glemte", "sendt", "sover", "beskytte", "ærlig", "send", "end", "slutte",
        "fik", "leder", "ordre", "passe", "sto", "vare", "født", "flink",
        "falt", "traff", "vant", "skrev", "kamp", "dyr", "hvite", "råd",
        "sjekk", "legger", "lide", "beskjed", "prate", "fanden", "plan", "svart",
        "stolt", "lys", "stikk", "vinner", "lot", "meter", "føle", "skriver",
        "fortsette", "mister", "ordne", "person", "skatt", "høyt", "spill", "nydelig",
        "kutt", "paris", "sjefen", "kompis", "skaffe", "forhold", "glemt", "midt",
        "paul", "ære", "kontakt", "drøm", "flytte", "hånden", "elske", "glemme",
        "dumme", "brug", "løs", "fest", "alvorlig", "aften", "vinne", "miste",
        "bob", "smart", "drep", "lukk", "skadet", "rolle", "stans", "opptatt",
        "film", "johnny", "lykkelig", "sulten", "agent", "vanlig", "forstått", "ødelagt",
        "tony", "annerledes", "snu", "absolutt", "sov", "bill", "ødelegge", "halv",
        "øye", "mennene", "sju", "forelsket", "interessant", "søt", "levende", "jaså",
        "ligge", "sjekke", "ene", "sterk", "filmen", "mening", "dessverre", "professor",
        "kaste", "lag", "gøy", "pen", "løytnant", "merkelig", "sprø", "kalle",
        "drikker", "plutselig", "kjørte", "øyne", "fru", "brukt", "skål", "syntes",
        "enig", "heldig", "deler", "kaster", "folkens", "prøvd", "skip", "håret",
        "kast", "lagt", "kyss", "arbeid", "jul", "respekt", "hopp", "interessert",
        "spor", "trekk", "gar", "tredje", "innen", "pistol", "stakkars", "lært",
        "fortsetter", "eier", "giv", "konge", "vide", "oberst", "personlig", "møtt",
        "båten", "selge", "blå", "kontroll", "tilgi", "ven", "skat", "billy",
        "het", "både", "måned", "flytt", "verste", "bekymre", "betalt", "kult",
        "bevis", "hår", "fine", "taler", "frøken", "blant", "fører", "slått",
        "starter", "tegn", "omkring", "fars", "svin", "gav", "etterpå", "forlate",
        "forandret", "hjalp", "morges", "lik", "president", "vist", "fange", "frisk",
        "engelsk", "bestemt", "mary", "selger", "hvilke", "forrige", "stemme", "ekstra",
        "slutter", "bad", "ordentlig", "glede", "usa", "tjener", "karer", "velge",
        "leke", "takke", "ordner", "moro", "kvitt", "truffet", "sarah", "bedt",
        "merke", "iblant", "hel", "bobby", "dean", "bortsett", "spist", "drømmer",
        "makt", "london", "enten", "stopper", "stakk", "starte", "tjene", "herren",
        "dele", "ren", "angrep", "festen", "bilder", "ringt", "lest", "klær",
        "bildet", "enhver", "elskling", "kate", "faller", "musikk", "fbi", "bry",
        "frokost", "leser", "synge", "besøk", "slag", "nervøs", "varmt", "forresten",
        "bar", "naturligvis", "tilhører", "kjøper", "penge", "kjempe", "liksom", "gravid",
        "type", "omtrent", "trygg", "styrke", "høy", "adjø", "menneskene", "mål",
        "kamerat", "varm", "mord", "ende", "forferdelig", "san", "gata", "armen",
        "hundre", "lunsj", "jim", "unnskyldning", "taper", "låne", "fullt", "robert",
        "beina", "gratis", "trist", "mod", "mester", "svare", "kjæreste", "bank",
        "håp", "inntil", "selskap", "nøyaktig", "sikre", "derfra", "trøbbel", "stand",
        "røde", "rent", "martin", "bestemmer", "prater", "tommy", "spis", "krever",
        "inni", "thomas", "sann", "richard", "begynt", "minst", "tull", "henry",
        "hvit", "overraskelse", "fryktelig", "kontor", "nødvendig", "betjent", "rød", "trenge",
        "fart", "altfor", "chuck", "innom", "boken", "føre", "flaks", "reis",
        "blåser", "direkte", "våkne", "kall", "deilig", "ansvar", "street", "giver",
        "dekk", "forsvinn", "beholde", "overleve", "rører", "åpner", "vilje", "start",
        "støtte", "rene", "trygt", "minutt", "ender", "nærmer", "bevise", "pleier",
        "forandre", "vakt", "hemmelig", "sersjant", "fanken", "major", "red", "ansikt",
        "morder", "trekke", "vill", "forlot", "nord", "systemet", "flytter", "likt",
        "utmerket", "bytte", "oppdaget", "fikse", "målet", "gale", "normalt", "glipp",
        "sees", "lete", "sikkerhet", "leste", "vin", "ulykke", "kjenne", "dama",
        "bestemor"
      ],
      music: [
        "sang", "kor", "band", "gitar", "piano", "tromme", "fløyte", "fiolin",
        "radio", "konsert", "danse", "rytme", "melodi", "plate", "artist", "mikrofon",
        "høyttaler", "refreng", "vers", "scene"
      ],
      art: [
        "kunst", "farge", "maleri", "tegning", "blyant", "pensel", "lerret", "plakat",
        "bilde", "ramme", "museum", "skisse", "form", "mønster", "foto", "figur",
        "leire", "papir", "lim", "saks"
      ],
      books: [
        "bok", "side", "kapittel", "forfatter", "lese", "eventyr", "roman", "dikt",
        "bibliotek", "bokhylle", "omslag", "tittel", "historie", "helt", "skurk", "brev",
        "avis", "blad", "ordbok", "notat"
      ],
      places: [
        "Oslo", "Bergen", "Trondheim", "Stavanger", "Tromsø", "Norge", "by", "gård",
        "fjell", "strand", "skog", "park", "butikk", "kafe", "kino", "kirke",
        "bro", "vei", "plass", "stasjon"
      ],
      food: [
        "brød", "ost", "melk", "egg", "smør", "eple", "banan", "potet",
        "gulrot", "kjøtt", "suppe", "pizza", "taco", "kaffe", "te", "vaffel",
        "bolle", "is", "sjokolade", "brunost", "pølse", "ris", "pasta"
      ],
      people: [
        "mor", "far", "barn", "venn", "nabo", "lærer", "lege", "sjef",
        "elev", "politi", "kokk", "bonde", "sanger", "skuespiller", "pilot", "tannlege",
        "frisør", "servitør", "bror", "søster"
      ]
    },
    medium: {
      general: [
        "dugnad", "matpakke", "rushtid", "sparkesykkel", "bunad", "påskeferie", "hyttetur", "skitur",
        "lommelykt", "paraply", "barnehage", "videregående", "kommune", "valgkamp", "fergekø", "bompenger",
        "tidsfrist", "abonnement", "kvittering", "forsikring", "leiekontrakt", "kollektivtransport", "søppelsortering", "strømregning",
        "nabovarsel", "fartsgrense", "knapt", "treffer", "eksempel", "farten", "informasjon", "munn",
        "bære", "bygge", "mark", "topp", "ihjel", "syv", "natta", "hore",
        "kysse", "england", "hull", "tilfelle", "ild", "javel", "forsøk", "blodet",
        "skriv", "sur", "kalles", "stein", "velger", "ler", "selvmord", "skudd",
        "hils", "spennende", "løgn", "roger", "kurs", "unngå", "hvile", "sykehus",
        "hoppe", "evig", "lure", "kraft", "luft", "nekter", "lette", "løper",
        "planer", "smil", "morsom", "skyldig", "soldat", "valgt", "sheriff", "lave",
        "fornøyd", "sjel", "kar", "kjøpt", "charles", "ferie", "bærer", "sen",
        "scott", "bond", "lyve", "åpen", "stiller", "eldre", "pust", "gull",
        "and", "stanse", "fader", "bestefar", "uskyldig", "lettere", "båt", "teller",
        "avtalen", "hendt", "skjebne", "stjele", "rike", "tanker", "bange", "oppdrag",
        "fienden", "leker", "bråk", "varme", "pike", "overfor", "arbeider", "fullstendig",
        "danser", "love", "røre", "kalt", "fikser", "slett", "hellige", "ettermiddag",
        "ordnet", "ødela", "drit", "løgner", "titt", "igjennom", "carl", "purk",
        "svarer", "fatter", "tør", "jord", "amerikansk", "rik", "brødre", "stykke",
        "foreldre", "styre", "data", "fredag", "pause", "pakke", "søtt", "chicago",
        "alder", "drap", "rask", "lade", "minne", "nåde", "halvt", "slem",
        "california", "les", "iallfall", "knust", "kald", "city", "partner", "spesiell",
        "dukker", "hank", "røyk", "visse", "verken", "nemlig", "college", "hilse",
        "neppe", "nyt", "besøke", "bildene", "kilo", "klasse", "skru", "virke",
        "greie", "blomster", "skam", "lort", "dust", "boka", "søker", "dans",
        "løse", "tøff", "hær", "tante", "hemmelighet", "stil", "sørge", "tolv",
        "gange", "bud", "kim", "fjerne", "ifra", "lange", "van", "daniel",
        "lede", "puste", "takket", "mørke", "victor", "bety", "sør", "banen",
        "savne", "arthur", "leilighet", "tydeligvis", "prat", "lufta", "spøk", "lee",
        "beinet", "kule", "fanger", "etasje", "frihet", "tross", "behold", "diskutere",
        "los", "presentere", "drikk", "søvn", "politimann", "vitne", "drive", "bringer",
        "sørg", "låst", "planlagt", "ide", "kilometer", "karen", "hopper", "skapt",
        "bryter", "oppdraget", "forvirret", "mors", "glade", "turen", "endre", "blind",
        "bryte", "verst", "driter", "simon", "tape", "privat", "vanligvis", "star",
        "baren", "tillatelse", "kle", "bein", "stod", "samle", "kjørt", "fransk",
        "hevn", "kniv", "gjett", "regel", "bringe", "smak", "tekst", "null",
        "tvil", "knulle", "voksen", "gjemme", "kjedelig", "latterlig", "rekke", "uka",
        "samtidig", "mulighet", "bombe", "lørdag", "begynn", "løfte", "don", "jacob",
        "grei", "kjemper", "jævelen", "område", "hode", "tja", "rar", "kødd",
        "arbeide", "phil", "penny", "hard", "prosent", "kylling", "vits", "tenner",
        "solgt", "pete", "syn", "møde", "delen", "vunnet", "kopp", "tidspunkt",
        "flotte", "knuse", "skaff", "levere", "søte", "mandag", "pas", "gråt",
        "våken", "kong", "spar", "modig", "ensom", "per", "alice", "mottatt",
        "team", "tanke", "vest", "ond", "majestet", "press", "sakte", "gjeng",
        "nøye", "angeles", "stjerne", "følelse", "hotell", "sara", "ligg", "skjule",
        "skape", "tviler", "vidunderlig", "grund", "panikk", "roy", "hjel", "adgang",
        "forslag", "ålreit", "henge", "sverd", "bestemme", "brian", "forsvinne", "posisjon",
        "slappe", "dog", "publikum", "bryllup", "kropp", "banke", "dronning", "ansvarlig",
        "prinsesse", "søndag", "hitler", "kode", "situasjon", "alvor", "falle", "ofre",
        "lyd", "dreng", "forsto", "gruppe", "trøtt", "fjern", "bie", "europa",
        "lukket", "tosk", "spurt", "lek", "lås", "vaske", "dreier", "dage",
        "fot", "fat", "banker", "rosa", "sporet", "roma", "beskytter", "mareritt",
        "pga", "ovenpå", "fjor", "pasient", "skaper", "late", "adam", "amen",
        "prins", "forklaring", "leonard", "rapport", "runde", "avisen", "matt", "sekund",
        "offer", "energi", "smith", "styrer", "lytter", "bag", "senator", "grader",
        "ferd", "heit", "flaske", "smaker", "kjole", "handle", "røyker", "cent",
        "tett", "forlatt", "louis", "lykkes", "kamera", "fremmed", "brenne", "øst",
        "skifte", "luke", "frankrike", "naken", "gråte", "lord", "marcus", "dna",
        "helgen", "forbudt", "halve", "super", "fiender", "samtale", "trykk", "erfaring",
        "drev", "hjerne", "drakk", "unntatt", "normal", "medisin", "vennlig", "manns",
        "vegne", "dersom", "later", "cia", "årsak", "pene", "skremme", "rock",
        "job", "møt", "sterkt", "stygg", "julie", "post", "filmer", "veier",
        "felle", "hagen", "forsvare", "hellere", "elendig", "eks", "anelse", "stoff",
        "kul", "liste", "dekning", "perfekte", "skritt", "satan", "vold", "grønne",
        "feire", "teknisk", "uvanlig", "skilt", "velsigne", "rettferdig", "søren", "kjøp",
        "årevis", "merker", "ekteskap", "snille", "dekker", "bliv", "jag", "miller",
        "sider", "føttene", "tomme", "ann", "ombord", "bestemte", "skjønne", "mil",
        "regne", "eksisterer", "forestille", "still", "ifølge", "retning", "angriper", "lader",
        "bit", "mars", "media", "leger", "hunder", "brutt", "spilt", "signal",
        "jenny", "biter", "operasjon", "enkel", "hindre", "dop", "lavt", "champagne",
        "flykte", "behandlet", "kontrollere", "kjekk", "falsk", "avslutte", "endret", "felles",
        "brøt", "delta", "river", "avstand", "drømme", "fulgt", "dyktig", "forstyrrer",
        "tomt", "takle", "verd", "stjeler", "torsdag", "advarsel", "erik", "fortjent",
        "tyv", "forskjell", "rocky", "jomfru", "høyhet", "nigger", "sæt", "vender",
        "jakt", "fjerde", "fungere", "plikt", "engel", "lady", "drukket", "falske",
        "offentlig", "størrelse", "typisk", "monsieur", "innenfor", "high", "bravo", "mirakel",
        "spre", "dekke", "naturlig", "latt", "johnson", "beskjeden", "tydelig", "rømme",
        "slet", "com", "fotball", "sies", "løsning", "gjenta", "tilbud", "nytte",
        "historier", "fryser", "allikevel", "vokse", "personlige", "sjalu", "svak", "bensin",
        "geni", "monster", "uhell", "pund", "grav", "brent", "skjønt", "francisco",
        "parker", "sjelden", "takknemlig", "skylden", "dømt", "vende", "alarm", "korrekt",
        "brukes", "behov", "slemme", "behandler", "sannsynligvis", "carter", "blås", "åssen",
        "harold", "fiende", "magi", "rydde", "fløy", "sort", "stygt", "jean",
        "grave", "villig", "forbindelse", "håpe", "vilt", "forholdet", "stan", "plage",
        "laura", "program", "hjulpet", "linje", "fakta", "rare", "pluss", "charlotte",
        "samler", "hud", "måter", "svømme", "kriger", "drosje", "stilig", "voksne",
        "klem", "sean", "helsike", "urolig", "restaurant", "røyke", "oppmerksomhet", "gjemt",
        "junior", "komplisert", "behandle", "trygge", "tim", "humør", "hullet", "hustru",
        "tap", "nære", "treffes", "gris", "kake", "tyskland", "spare", "seier",
        "lytte", "sykdom", "roper", "fatt", "omgang", "fritt", "vekke", "smake",
        "kopi", "høye", "stått", "let", "språk", "oppgave", "kler", "løft",
        "angripe", "menneskelig", "romantisk", "avdeling", "storm", "tirsdag", "bane", "nivå",
        "eiendom", "ment", "våkn", "hill", "viss", "fylt", "medlem", "bekreftet",
        "indre", "følt", "deretter", "trakk", "florida", "sanne", "dørene", "bånd",
        "gjette", "melding", "temmelig", "heldigvis", "gudskjelov", "tall", "rotet", "berømt",
        "dobbelt", "amerikanere", "ånd", "lekker", "stig", "helen", "boston", "treet",
        "livs", "lær", "beholder", "tungt", "hat", "bla", "billig", "skitne",
        "strømmen", "trett", "undersøke", "ledig", "hysj", "dommeren", "gjeld", "sid",
        "ideer", "tysk", "beskyttelse", "kina", "gården", "innrømme", "king", "billetter",
        "sprenge", "lokale", "huden", "fylle", "talent", "hav", "karriere", "mus",
        "fan", "beskyttet", "homse", "levd", "miami", "universitetet", "sving", "forsvar",
        "gjest", "ført", "sukker", "sola", "stygge", "skynde", "hvil", "christian",
        "unnskylde", "øen", "utsatt", "jan", "styr", "eksamen", "test", "linda",
        "krav", "veit", "hell", "underlig", "teddy", "brukket", "stilling", "greiene",
        "kutte", "begravelse", "sommer", "nina", "mennesket", "dukke", "ukjent", "interesse",
        "adresse", "velg", "utro", "jordan", "planet", "akter", "skjønnhet", "kommandør",
        "øyeblikkelig", "bestille", "angre", "skar", "japan", "broder", "system", "ran",
        "slaget", "melde", "skifter", "afrika", "narkotika", "mad", "kraftig", "snur",
        "punkt", "rad", "service", "rive", "puster", "matte", "smule", "øre",
        "sår", "gass", "drømt", "pakk", "jackson", "rørt", "fett", "sommeren",
        "stenge", "homer", "karl", "langsomt", "sta", "triks", "blaffen", "lav",
        "hvitt", "tullet", "handlet", "lider", "klatre", "oktober", "moderne", "sparke",
        "dallas", "anthony", "skjære", "galskap", "advare", "emma", "sagen", "onsdag",
        "cæsar", "ens", "brann", "muligens", "pinlig", "beslutning", "midnatt", "forstyrre",
        "tung", "besatt", "femte", "grønn", "planlegger", "tilby", "passende", "fremtid",
        "gidder", "feite", "kledd", "spark", "lat", "las", "tilfeldigvis", "isen",
        "presse", "bundet", "spion", "behandling", "framtid", "skjorte", "leit", "kreft",
        "tvang", "bevæpnet", "sjokk", "oversatt", "sikte", "klient", "tillit", "fitte",
        "klager", "avisene", "dæven", "narr", "morn", "stukket", "spore", "sal",
        "fantasi", "kilden", "benjamin", "tilbringe", "skriker", "nød", "derek", "boks",
        "inspektør", "arm", "lederen", "steg", "leie", "kontakte"
      ],
      music: [
        "korps", "joik", "Hardingfele", "trekkspill", "munnspill", "slagverk", "bassgitar", "musikkvideo",
        "lydprøve", "festspill", "folkemusikk", "opera", "jazzklubb", "allsang", "noter", "toneart",
        "dirigent", "orkester", "låtskriver", "musikkfestival", "danseband", "russelåt", "spellemannpris", "vinylplate"
      ],
      art: [
        "Munch", "skulptur", "nasjonalromantikk", "akvarell", "grafikk", "keramikk", "tresnitt", "utstilling",
        "galleri", "kunstner", "portrett", "landskap", "kollasj", "gatekunst", "installasjon", "kunstkritiker",
        "kunsthistorie", "komposisjon", "perspektiv", "motiv", "atelier", "vernissasje", "kunsthåndverk", "glassblåsing"
      ],
      books: [
        "krimroman", "Ibsen", "Hamsun", "Bjørnson", "barnebok", "lydbok", "ebok", "novelle",
        "biografi", "bokklubb", "forlag", "bokhandel", "forteller", "hovedperson", "spenning", "bokmerke",
        "oversetter", "litteratur", "manus", "sitat", "anmeldelse", "sagn", "folkediktning"
      ],
      places: [
        "hytte", "skjærgård", "Nord-Norge", "Lofoten", "Geiranger", "Kristiansand", "Ålesund", "Bodø",
        "Drammen", "Fredrikstad", "Sørlandet", "Vestlandet", "Østlandet", "Finnmark", "Røros", "Hardanger",
        "Dovre", "Rondane", "bygd", "tettsted", "rådhus", "flyplass", "fergekai", "tursti"
      ],
      food: [
        "rømmegrøt", "pinnekjøtt", "skillingsbolle", "kjøttkake", "fiskekake", "lapskaus", "fiskesuppe", "rekesmørbrød",
        "knekkebrød", "leverpostei", "makrell i tomat", "spekemat", "fenalår", "multekrem", "riskrem", "kransekake",
        "sveler", "raspeball", "komle", "koldtbord", "pannekake", "bløtkake", "wienerbrød"
      ],
      people: [
        "ordfører", "programleder", "journalist", "fotograf", "sykepleier", "barnehagelærer", "snekker", "rørlegger",
        "elektriker", "advokat", "dommer", "forsker", "student", "pensjonist", "turist", "frivillig",
        "trener", "landslagsspiller", "influencer", "komiker", "rektor", "prest", "brannmann", "vekter"
      ]
    },
    hard: {
      general: [
        "allemannsretten", "fellesferie", "formueskatt", "Janteloven", "forbrukerrådet", "arbeidsgiveravgift", "folketrygden", "grunnlovsdag",
        "samfunnsdebatt", "høringsfrist", "sivilombudet", "statsbudsjett", "fylkeskommune", "skatteoppgjør", "trygdeoppgjør", "beredskapslager",
        "personnummer", "verneplikt", "konsesjon", "likestillingsombud", "klagefrist", "borettslag", "sameie", "husleietvist",
        "livets", "rakk", "firma", "antagelig", "nysgjerrig", "arrestere", "von", "grønt",
        "steng", "teknologi", "russland", "ellen", "canada", "ondskap", "milde", "stiger",
        "strøm", "tåpelig", "skyss", "søk", "søta", "usas", "dødelig", "hundrevis",
        "overta", "vasker", "straff", "tunge", "katastrofe", "juli", "kinesisk", "raymond",
        "homo", "kokain", "forlat", "bevegelse", "ambulanse", "amanda", "male", "studere",
        "sikret", "pisse", "detaljer", "synder", "værelse", "amerikaner", "green", "grand",
        "melder", "enorm", "elleve", "tilstand", "teori", "stanley", "framover", "trening",
        "tilfeldig", "krangle", "lisbeth", "opplevd", "invitere", "syng", "dress", "feit",
        "japansk", "house", "formue", "avgjørelse", "venninne", "kunde", "desto", "skift",
        "tips", "tester", "skitten", "rykte", "gate", "fornuftig", "olje", "video",
        "konstabel", "skygge", "sans", "halvtime", "sikt", "rygg", "berlin", "ektemann",
        "hal", "idag", "jersey", "utstyr", "gule", "kanal", "ruby", "helikopter",
        "klage", "himmel", "sittende", "forbrytelse", "nedover", "tillegg", "trukket", "natur",
        "hjemmefra", "ekspert", "utenom", "avgjort", "avsluttet", "slip", "oppføre", "held",
        "øve", "klok", "utviklet", "sinne", "sebastian", "forsøke", "tvunget", "kristus",
        "spansk", "september", "politikk", "tiger", "mordere", "gjem", "alkohol", "teit",
        "lønn", "vart", "stede", "heks", "landets", "dyrene", "oppi", "overgi",
        "forsikre", "madame", "trykke", "rase", "bestilt", "skrik", "sloss", "fetter",
        "led", "tilbød", "fødselsdag", "overbevise", "jamen", "fremme", "fortid", "drage",
        "italiensk", "vend", "hoved", "skille", "spania", "avsløre", "cirka", "maskin",
        "luk", "sørover", "telle", "forskning", "bortkastet", "eve", "barbara", "bukser",
        "søke", "fjols", "cindy", "spil", "ideen", "trives", "jakte", "storartet",
        "kvalm", "anderson", "røv", "mektig", "bomber", "julia", "sand", "forhandle",
        "tisse", "begå", "innså", "pastor", "sentrum", "kyle", "rotte", "løfter",
        "fyller", "island", "ører", "santa", "oppnå", "fæle", "kjerring", "houston",
        "antakelig", "bind", "låse", "nevne", "niks", "lyn", "grå", "jøde",
        "sparer", "bygning", "utføre", "avgjøre", "biff", "oppførsel", "overraske", "hengt",
        "dømme", "døv", "fordel", "politisk", "bakover", "blikk", "dusj", "november",
        "presis", "smarte", "reparere", "fornuft", "trolig", "dusin", "baseball", "hate",
        "cuba", "stolthet", "gid", "kollega", "pikk", "etterforsker", "våt", "rev",
        "grad", "samvittighet", "tørst", "brakk", "baker", "betydning", "fordømt", "sverige",
        "begått", "andel", "lande", "stu", "bena", "nyter", "vask", "fingeravtrykk",
        "duke", "donna", "øker", "forklar", "slaver", "begrave", "intelligent", "senk",
        "sinnssyk", "beder", "molly", "oscar", "siktet", "humor", "forsvarer", "billett",
        "føtter", "taylor", "handling", "modell", "tilgang", "hilsen", "tekster", "oppdager",
        "anledning", "brenn", "rot", "county", "tøffe", "motstand", "lur", "plukke",
        "trent", "støv", "nordover", "slange", "brudd", "grusom", "snut", "praktisk",
        "forandring", "magisk", "skadd", "kjennes", "enhet", "ali", "tjent", "bevare",
        "norske", "forberede", "avhengig", "juni", "hang", "godta", "utført", "utvei",
        "sigarett", "korporal", "harris", "psykiater", "harde", "forretning", "klokke", "midlertidig",
        "albert", "militære", "jonathan", "serien", "virus", "tvinger", "uskadd", "menig",
        "buksa", "mal", "mate", "status", "forrest", "brooklyn", "jennifer", "clark",
        "egypt", "inntrykk", "forstyrret", "vennskap", "søppel", "eieren", "trær", "sludder",
        "bingo", "forbannelse", "presser", "art", "tynn", "uniform", "trykker", "cola",
        "goddag", "frekk", "feste", "turner", "blande", "kjempebra", "hverken", "svi",
        "sydney", "tau", "forsiktige", "vurdere", "lloyd", "admiral", "brakt", "ass",
        "golf", "hor", "hugo", "vand", "elvis", "dytt", "betal", "bart",
        "celle", "krone", "heroin", "daggry", "bursdag", "kansas", "menneskelige", "grep",
        "prosjekt", "tropp", "brydde", "jager", "mistenkt", "akseptere", "overstått", "feiging",
        "brakte", "vanvittig", "levert", "rope", "sport", "leken", "fiske", "kors",
        "kutter", "moskva", "anderledes", "innsats", "skremt", "idiotisk", "sliter", "lån",
        "sprit", "rita", "tokyo", "kne", "skjønn", "delt", "tank", "minus",
        "bjørn", "festlig", "bitt", "maler", "kilde", "fortapt", "mørk", "verdig",
        "blåse", "helter", "drite", "rumpe", "nate", "makker", "helg", "svær",
        "binde", "spøkelse", "penn", "overens", "anklager", "oppleve", "konsentrer", "mai",
        "telefoner", "tørr", "latter", "stilt", "stanser", "hjerter", "ammunisjon", "dermed",
        "hensikt", "filme", "applaus", "spørger", "holdes", "mene", "vekt", "følsom",
        "hertil", "demon", "feig", "røret", "rop", "vedde", "spenn", "klippe",
        "leverer", "håndtere", "friske", "leir", "mist", "femti", "vogn", "fyll",
        "beveg", "ford", "east", "sun", "summer", "eva", "overtale", "flukt",
        "fester", "blinde", "merr", "armer", "hurra", "måltid", "midler", "feber",
        "besøker", "raske", "sjåfør", "forbered", "medisinsk", "borgermesteren", "tess", "vesen",
        "vodka", "søstera", "kødde", "populær", "forræder", "råtne", "forhindre", "bestandig",
        "partnere", "franklin", "dyret", "profesjonell", "mystisk", "hensyn", "margaret", "uventet",
        "konstant", "nyttig", "ulv", "seattle", "ape", "detroit", "flau", "kick",
        "svømmer", "stillhet", "grundig", "fullføre", "august", "lam", "fisker", "bokser",
        "base", "otto", "fattig", "krysse", "knyttet", "pat", "løslatt", "tålmodig",
        "forlovede", "handel", "lovlig", "dumpet", "kjapp", "blander", "india", "stress",
        "trøst", "teppe", "galning", "omvendt", "javisst", "skamme", "vesten", "ettersom",
        "frykte", "uflaks", "hodepine", "fremover", "kur", "spart", "knep", "last",
        "begikk", "elever", "behagelig", "nytter", "reaksjon", "koma", "fornærmet", "istedenfor",
        "gaven", "dukk", "risiko", "lars", "forsøkt", "troll", "trengt", "motta",
        "daniels", "godkjent", "ødelegg", "nedenunder", "vrede", "leide", "robot", "benet",
        "fangen", "føl", "skjær", "blomst", "håndjern", "vitenskap", "styrbord", "fremad",
        "gjengjeld", "artig", "fenrik", "overtar", "straffet", "vri", "lastebil", "landsby",
        "avgjør", "gin", "forbli", "virginia", "south", "knapp", "klatrer", "piper",
        "løser", "søm", "seile", "baltimore", "akt", "havne", "straffe", "høflig",
        "rekkevidde", "serie", "beskrive", "dessert", "barnebarn", "rane", "bekrefte", "tal",
        "beach", "montana", "posen", "oppfør", "betaling", "haug", "kjenn", "dobbel",
        "treff", "utsikt", "kvart", "teste", "øverst", "sekretær", "heng", "antonio",
        "kryp", "bruden", "bær", "tillate", "plukker", "finger", "lake", "fingre",
        "rute", "tilgivelse", "pose", "nekte", "dragen", "lojalitet", "nærmest", "alternativ",
        "uhyre", "samling", "long", "krise", "robin", "lavere", "gevær", "felt",
        "overfalt", "victoria", "jage", "rømt", "gammeldags", "innbrudd", "keiser", "samfunn",
        "lillebror", "lengst", "lev", "jaha", "kasse", "vinde", "grip", "begravd",
        "opptak", "arr", "sug", "luther", "teamet", "mobil", "billede", "pussig",
        "skåret", "ekle", "mel", "bede", "tragisk", "opprør", "halvveis", "kaker",
        "mynt", "sjette", "foreløpig", "intervju", "konsentrere", "fatte", "frelse", "right",
        "sjakk", "forestilling", "gress", "bly", "studerte", "salg", "egoistisk", "bang",
        "terapi", "helmer", "identifisere", "livstid", "delene", "føde", "koselig", "tørke",
        "fiks", "politifolk", "hete", "antall", "favoritt", "smile", "orleans", "peker",
        "kvitte", "mississippi", "brus", "kane", "formål", "øvelse", "belønning", "spy",
        "virkelighet", "rådgiver", "nese", "ytre", "satse", "joseph", "dyp", "bur",
        "spent", "låser", "patetisk", "tas", "episode", "krigere", "cash", "museet",
        "vekker", "brud", "stella", "hule", "skjold", "martha", "oversettelse", "skarp",
        "fredelig", "myk", "teater", "høyde", "dropp", "kanin", "detektiv", "klør",
        "tispe", "master", "enestående", "syne", "konto", "droppe", "lekte", "søkte",
        "frukt", "avbryte", "uti", "uttrykk", "kos", "smakt", "sjøl", "pang",
        "tipper", "transport", "diger", "kreve", "vred", "verdi", "peiling", "foreslå",
        "lokal", "tjukken", "ridder", "australia", "verk", "aktivitet", "hop", "hurtig",
        "guvernør", "lester", "bade", "kjemp", "negativ", "fase", "bønn", "maken",
        "skuffe", "drukne", "svikte", "edru", "tonen", "paradis", "svinger", "overbetjent",
        "maske", "pater", "lyse", "korte", "rulle", "true", "januar", "caroline",
        "stige", "flyter", "påvirket", "identitet", "mangel", "forstod", "militær", "karakter",
        "spring", "kung", "aktivert", "styrte", "hjørne", "mon", "logisk", "bernard",
        "ira", "konkurranse", "oppover", "vinen", "påvirke", "oppdage", "rydd", "kompani",
        "aviser", "indianere", "daglig", "vestover", "passere", "plasser", "gul", "streng",
        "puls", "førstebetjent", "ønsk", "slås", "sjenert", "knipe", "sårede", "ruth",
        "massevis", "borgermester", "bekjempe", "apropos", "beroligende", "opplevelse", "mannskap", "herlig",
        "brenner", "smerte", "løpe", "jævlig", "trekker", "rose", "frykt", "dratt",
        "året", "dessuten", "glass", "løy", "million", "suksess", "rimelig", "klapp",
        "boy", "trykket", "kvarter", "sorg", "ilden", "boss", "vietnam", "kontrakt",
        "koste", "kuler", "innse", "lukke", "nevnt", "dom", "kart", "sjarmerende",
        "skjorta", "ansatt", "sinn", "knuser", "april", "computer", "tulling", "overlevende",
        "kursen", "skitt", "sannhet", "støtter", "grace", "heie", "vampyr", "knappen",
        "fæl", "kennedy", "skrike", "slave", "risikere", "fysisk", "freddy", "nyte",
        "russisk", "fornøyelse", "bring", "piller", "diego", "evighet", "rettferdighet", "faktum",
        "urettferdig", "rede"
      ],
      music: [
        "Dovregubbens hall", "Peer Gynt-suite", "black metal", "Edvard Grieg", "Kirsten Flagstad", "Arne Nordheim", "Ole Bull", "Sissel Kyrkjebø",
        "a cappella", "polyfoni", "kontrapunkt", "symfoniorkester", "kammermusikk", "musikkteori", "folketone", "slåttemusikk",
        "hardingfeleslått", "improvisasjon", "arrangement", "mastering", "stemmeskifte", "overtoner"
      ],
      art: [
        "Vigelandsparken", "stavkirke", "rosemaling", "treskjæring", "Osebergskipet", "Nidarosdomen", "ekspresjonisme", "modernisme",
        "kubisme", "surrealisme", "litografi", "silketrykk", "freskomaleri", "altertavle", "brukskunst", "kunstbiennale",
        "konseptkunst", "kurator", "proveniens", "restaurering", "ikonografi", "barokk"
      ],
      books: [
        "Sult", "Markens grøde", "Kristin Lavransdatter", "Et dukkehjem", "Peer Gynt", "Sigrid Undset", "Tarjei Vesaas", "Cora Sandel",
        "Johan Borgen", "Dag Solstad", "Jon Fosse", "Herbjørg Wassmo", "Knausgård", "naivisme", "realisme", "etterkrigslitteratur",
        "metafor", "undertekst", "fortellerperspektiv", "allusjon", "litteraturkritikk", "bokmål", "nynorsk", "riksmål"
      ],
      places: [
        "Jotunheimen", "Svalbardtraktaten", "Preikestolen", "Trollstigen", "Hardangervidda", "Finnmarksvidda", "Saltstraumen", "Atlanterhavsveien",
        "Nordkapp", "Kautokeino", "Rjukan", "Verdens Ende", "Helgelandskysten", "Besseggen", "Lysefjorden", "Trollheimen",
        "Sunnmørsalpene", "Vesterålen", "Senja", "Femunden", "Setesdal", "Telemarkskanalen"
      ],
      food: [
        "lutefisk", "rakfisk", "fårikål", "nøkkelost", "Vestlandslefse", "gomme", "sodd", "møsbrømlefse",
        "boknafisk", "klippfisk", "tørrfisk", "surkål", "flatbrød", "røkelaks", "gravlaks", "elgkarbonade",
        "reinsdyrstek", "moltesyltetøy", "tyttebærsyltetøy", "geitost", "pultost", "akevitt", "karsk", "fårikålens dag"
      ],
      people: [
        "polfarer", "statsforvalter", "stortingsrepresentant", "riksantikvar", "riksmekler", "riksadvokat", "sivilingeniør", "statssekretær",
        "byrådsleder", "fylkesordfører", "sametingspresident", "nobelprisvinner", "språkviter", "arkeolog", "meteorolog", "ombudsmann",
        "fagforeningsleder", "høyesterettsdommer", "kommentator", "kulturminister", "fjellfører", "redningsmann", "bunadstilvirker", "eventyrsamler"
      ]
    }
  };

  window.ALIAS_CATEGORIES = {
    all: "Alle",
    general: "Blandet",
    music: "Musikk",
    art: "Kunst",
    books: "Bøker",
    places: "Steder",
    food: "Mat",
    people: "Folk"
  };

  window.ALIAS_DIFFICULTIES = {
    easy: "Lett",
    medium: "Middels",
    hard: "Vanskelig"
  };

  window.ALIAS_WORDS = flattenWords(WORDS_BY_DIFFICULTY);

  function flattenWords(source) {
    var result = {};

    Object.keys(source).forEach(function (difficulty) {
      result[difficulty] = [];

      Object.keys(source[difficulty]).forEach(function (category) {
        source[difficulty][category].forEach(function (word) {
          result[difficulty].push({
            word: word,
            category: category
          });
        });
      });
    });

    return result;
  }
})();
